{{- if .Values.database.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.database.name }}-initdb
data:
  schema.sql: |
{{ .Files.Get "database/schema.sql" | indent 4 }}
  seed.sql: |
{{ .Files.Get "database/seed.sql" | indent 4 }}
{{- end }}
