{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.name }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.database.auth.rootPassword | quote }}
  mysql-database: {{ .Values.global.databaseName | quote }}
  mysql-user: {{ .Values.global.DBUSER | quote }}
  mysql-password: {{ .Values.global.DBPASS | quote }}
{{- end }}
