apiVersion: v2
name: shellbin
description: pastebin clone using a few microservices

type: application

version: 0.1.0

appVersion: "0.01"

depenedencies:
  - name: mysql
    version: "0.1"
    repository: file:///charts/mysql-chart
