apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dbservice.name }}
  labels:
    app: {{ .Values.dbservice.name }}
    date: "{{ now | unixEpoch }}"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.dbservice.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.dbservice.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.dbservice.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
      # serviceAccountName: {{ include "shellbin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.dbservice.name}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.registryUrl }}/{{ .Values.dbservice.image.repository }}:{{ .Values.dbservice.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.dbservice.image.pullPolicy }}
          command: ["sleep"]
          args: ["infinity"]
          # command: ["sh"]
          # args: ["entrypoint.sh"]
          env:
            - name: DBADDR
              value: {{ .Values.global.DBADDR }}
            - name: DBUSER
              value: {{ .Values.global.DBUSER }}
            - name: DBPASS
              value: {{ .Values.global.DBPASS }}
          ports:
            - name: internal-port
              containerPort: {{ .Values.dbservice.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.dbservice.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbservice.name }}
  labels:
    {{- include "shellbin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dbservice.service.type }}
  ports:
    - port: {{ .Values.dbservice.service.port }}
      targetPort: 7272
      protocol: TCP
      name: db-service-port
  selector:
    app: {{ .Values.dbservice.name }}