{{- if .Values.ncserver.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shellbin.serviceAccountName" . }}
  labels:
    {{- include "shellbin.labels" . | nindent 4 }}
  {{- with .Values.ncserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
