apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.toolServer.name }}
  labels:
    {{- include "shellbin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.toolServer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "shellbin.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shellbin.server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "shellbin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.toolServer.name}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.toolServer.image.repository }}:{{ .Values.toolServer.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.toolServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.toolServer.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.toolServer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.toolServer.name }}
  labels:
    {{- include "shellbin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.toolServer.service.type }}
  ports:
    - port: {{ .Values.toolServer.service.port }}
      targetPort: http
      protocol: TCP
      name: toolserver-port
  selector:
    app.kubernetes.io/name: {{ .Values.toolServer.name }}