apiVersion: v1
kind: Service
metadata:
  labels:
    app: ncserver
    app.kubernetes.io/managed-by: Helm
  name: ncserver-nodeport
  namespace: shellbin2
spec:
  clusterIP: 10.43.168.234
  clusterIPs:
    - 10.43.168.234
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 31362
      port: 6262
      protocol: TCP
      targetPort: 6262
  selector:
    app: ncserver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
